//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_DesenvolvimentoAplicacoes
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_Projeto_DAContainer : DbContext
    {
        public BD_Projeto_DAContainer()
            : base("name=BD_Projeto_DAContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Pessoa> Pessoa { get; set; }
        public virtual DbSet<Compra> Compra { get; set; }
        public virtual DbSet<DetalheCompra> DetalheCompra { get; set; }
        public virtual DbSet<Produto> Produto { get; set; }
        public virtual DbSet<TipoProduto> TipoProduto { get; set; }
        public virtual DbSet<Escola> Escola { get; set; }
        public virtual DbSet<Participacao> Participacao { get; set; }
        public virtual DbSet<Evento> Evento { get; set; }
        public virtual DbSet<Inscricao> Inscricao { get; set; }
        public virtual DbSet<Colaboracao> Colaboracao { get; set; }
    }
}
